== Un Egoisti Giga

// Un Hedo Prince
// Kapitula 2

// Last modified 201811280104

Singu po-meso-di, tem mu ki ex sko-do; plu infanti pa ki e sporta in horti de u Giga.

Id pa es u mega e kali horti; ko moli e kloro gra. Ci e la epi u gra pa sta plu flori simi
plu astro; e pa es mo-bi persika-dendro; in blasto-tem mu frakti ex ad in plu delika flori
de rosa e margari; e sperma-tem mu fero pluto frukti. Plu avi pa sedi epi plu dendro; e mu
pa kanta ta dulce; plu infanti pa sto sporta te audi mu. “Na es ta hedo ci!” mu pa voci ad
alelo.

Mo di u Giga pa veni versi. An pa ki ab te visita an ami un Kornisc homi-vora giga; an pa
resta kon an tem septi anua. Po septi anua an pa dice panto-ra; an pa volu dice; ka an
konversa pa es ge-limita; e an pa decide de ki versi ad auto kastela. Kron an pa ariva; an
pa vide plu infanti sporta in an horti.

“Qo-ka tu es ci?” an pa voci fo non-ami; e plu infanti pa dromo ab.

“Mi auto horti es mi auto horti,” pa dice u Giga; “ali-pe pote logi u-la; mi lice zero-pe
de sporta in id exklude mi auto.” Seqe-co, an pa tekto u fo alti mura peri id; e plu
monstra un info-taba.


