== Plu Transgresi-pe Fu Gene Puni

// Un Hedo Prince
// Kapitula 3

// Last modified 201811280104

An pa es u fo egoisti Giga.

Nu plu mali-fortuna infanti pa habe zero sporta-lo. Mu pa tenta sporta epi u via; sed u
via pa es fo pulve e ge-ple per plu sklero lito; e mu ne amo id. Mu pa vaga peri plu alti
mura po sko; e mu pa dice de u kali horti intra.

“Na pa es fo hedo la!” mu pa dice ad alelo.

Po-co, blasto-tem pa veni; panto-lo in landa; pa es plu pusi flori epi plu dendro e plu
pusi avi. Solo in horti de un egoisti Giga id dura es hiberna. Plu avi na pa volu kanta
la; kausa pa es zero infanti; e plu dendro no-memo de flori. Mo kron u kali flori pulsa ex
id kefa ex u gra; sed kron id pa vide un info-taba id pa este ta simpati de plu infanti; e
id pa glisa versi ad in suela; e pa somni. Solo bi persona pa este hedo; u nivi e u
krista. “Blasto-tem no-memo u-ci horti,” mu pa voci, “seqe-co, na fu eko ci holo anua.” U
nivi pa tegu u gra per fe mega leuko vesti; e u krista pa kroma singu dendro per argenti.
Mu pa invita u Boreo Venti de resta ko mu; e an pa veni. An pa es ge-vesti per plu pila; e
an pa soni un holo di peri un horti; e pa fla kata plu fumi-tubi. “U-ci es u delekta
loka,” an pa dice; “na nece invita u Grandina.” E u Grandina pa veni. Singu di tem tri
horo an pa bali se epi u stego de u kastela; a-kron an pa frakti maxi mero de plu lami-li;
po-co, an pa dromo peri e peri un horti iso tako de posi. An pa es ge-vesti per polio; e
an spira pa es iso glacia.

“Mi ne logi u kausa blasto-tem veni ta po-kron;” pa dice un Egoisti Giga; tem an pa sedi
para u fenestra e pa skope ex ad an frigi e leuko horti. “Mi spe; u klima nu-fu muta.”

Sed blasto-tem ne pa veni; ni un estiva. Sperma-tem pa dona kriso frukti a singu horti;
sed ad horti de u Giga fe pa dona zero-ra. “An es tro egoisti;” fe pa dice. Seqe-co, id pa
es panto-tem hiberna la; e u Boreo Venti e u Grandina; e u Krista e u Nivi kore peri e dia
plu dendro.

Mo matina u Giga pa kumbe vigi in an kli; kron an pa audi kali musika. Id pa soni ta dulce
ad an plu oti; an pa doxo; id es plu musika-pe de un An-regi pasa. Reali, id pa es u
fringila kanta extra an fenestra; sed an ne pa audi avi-kanta in an horti ex pre longi
tem; e id pa feno ad an de es u maxi kali musika in u munda. Po-co, u Grandina pa sto kore
supra an kefa; e u Boreo Venti pa sto fla; e u delicioso fragra veni ad an dia un aperi
fenestra. “Mi kredi blasto-tem nu veni;” pa dice u Giga; e an pa salta ex kli e pa skope
ex.

Qo-ra an pa vide?

An pa vide u sti mira vista. Dia u fora in u mura plu infanti pa repti in; e mu nu sedi in
plu rami de plu dendro. In singu dendro an pa pote vide; pa es u pusi infanti. E plu
dendro pa es ta hedo de habe plu infanti in mu itera; mu pa tegu se ko poli flori; e mu nu
gentili oscili mu braki supra plu kefa de plu infanti. Plu avi nu peti ci e la; e mu nu
kanta kon hedo; e plu flori nu skope ana dia u kloro gra; e mu nu ridi. Id pa es u kali
vista; sed in solo mo gono id dura es hiberna. Id pa es u maxi tele gono de un horti; e in
id pa sta u pusi ju-an. An pa es ta pusi; an ne pa pote tange plu rami de u dendro; e an
pa gresi peri id e pa lakrima forti. U mali-fortuna dendro pa dura es ge-tegu ko Krista e
nivi; e u Boreo Venti dura fla e soni supra id. “Skende ana! Pusi ju-an,” pa dice u
Dendro; e id pa klina kata id plu rami iso baso de posi; sed u ju-an pa es tro pusi.

U kardia de u Giga pa gene ma dulce tem an pa skope ex. “Mi pa du fo egoisti!” an pa dice.
“Nu mi ski; u kausa u blasto-tem ne pa veni ci. Mi fu loka u-la mali-fortuna pusi ju-an
epi un akro de u dendro; po-co, mi fu sti kade u mura; e mi horti fu es u sporta-lo pro
plu infanti panto-tem.” An pa este fo penite qod an pa face.

An pa repti kata u skala; e minus soni an pa ki ex ad in un horti. Sed kron plu infanti pa
vide an mu pa este fobo; e panto mu pa dromo ab; e un horti pa esce hiberna itera. Solo u
pusi ju-an ne pa dromo; kausa an plu oku pa es ple de plu lakrima e an ne pa vide u Giga
qi veni. U Giga fo gentili gresi poste an; an gentili pa prende an ad in an manu; e pa
loka an in u dendro. Imedia po-co, u dendro pa blasto ad in plu flori; e plu avi pa veni
te kanta epi id; e u pusi ju-an pa tensio ex an bi braki; e pa bali mu peri cervika de u
Giga; e pa oskula an. E kron plu hetero infanti pa vide u Giga nu ne es mali; mu pa dromo
versi; e ko mu pa veni u blasto-tem. “Id es tu horti nu, pusi infanti;” pa dice u Giga. E
an pa prende u mega peleki; e pa sti kade u mura. E mo-bi horo; tem plu persona ki ad
agora; mu pa vide u Giga nu sporta ko plu infanti in u maxi kali horti mu ali-kron pa
vide.

Un holo di mu pa sporta; e tem vespera mu veni te dice vale ad u Giga.

“Sed qo-lo tu pusi ami?” an pa dice. “U pusi ju-an; mi pa loka an in u dendro.” U Giga amo
an u maxi mega; kausa an pa oskula an.

“Na ne ski;” pa reakti plu infanti. “An pa ki ab.”

“Tu nece dice ad an; sura veni ci fu-di;” pa dice u Giga. Sed plu infanti pa dice; mu ne
ski an eko-lo; e pre u-la kron mu zero-kron pa vide an; e u Giga pa este fo non-hedo.

Singu po-meso-di; po sko; plu infanti pa veni te sporta kon u Giga. Sed mu zero-kron pa
vide itera u pusi ju-an qi u Giga ta filo. U Giga pa es fo gluko a panto infanti; sed an
pa fo volu vide an proto pusi ami; e an freqe pa dice de an. “Mi fo volu vide an itera!”
an freqe pa dice.

Poli anua pa pasa; e u Giga pa esce fo paleo e debili. Nu an ne pote sporta; vice-co, an
pa sedi in u mega braki-sedi-mo; e pa skope tem plu infanti sporta; e an pa admira an
horti. “Mi habe poli kali flori;” an pa dice. “Sed plu maxi kali flori es plu infanti.”

Mo hiberna matina an pa du skope ex an fenestra tem an pa vesti se. Nu an ne detesta un
hiberna; ka an ski; id es solo u somni de blasto-tem; e plu flori nu reposa.

Subito an pa frika an plu oku; este sti mira; an pa skope e pa skope. Veri, id pa es u sti
mira vista. In u maxi tele gono de an horti pa es u dendro; holo ge-ple per plu leuko
flori. Plu rami pa es kriso; e plu argenti frukti pa pende kata ex mu; e infra pa sta u
pusi ju-an qi an ta filo.

Kata u skala pa dromo u Giga; an pa este ta delekta e hedo. An pa peti trans u gra; e pa
veni proxi u ju-an. E kron an pa es fo proxi; an facia pa kresce rubi per koleri. E an pa
dice; “Qo-pe pa audacio de noku tu?” Ka plu meso de plu manu de u pusi ju-an pa monstra
plu marka ed bi aku; e plu marka de bi aku pa es epi an plu pedi.

“Qo-pe pa audacio de noku tu?” Pa fo voci u Giga; “dice a mi; e mi fu prende mi mega
gladia e cide an.”

“No!” pa reakti u ju-an: “sed plu-ci es plu noku de Filo.”

“Qo-pe tu es?” pa dice u Giga; e an pa este u strano respekti e sti mira; e an pa kade epi
plu genu ante u ju-an.

E u ju-an pa subo ridi ad u Giga; e an pa dice ad an; “tu mo-kron pa lase mi sporta in tu
horti; nu-di tu fu veni ko mi a mi horti; id es Paradiso.”

E kron plu infanti pa dromo in un horti u-la po-meso-di; mu pa detekti u Giga kumbe morta
infra u dendro qi pa es ge-ple per plu leuko flori.

