== Un Hedo Prince

// Un Hedo Prince
// Kapitula 1

// Last modified 201811280104

Alti supra u polita, epi un alti kolumni, pa sta u statua de un Hedo Prince. An pa es holo
ge-tegu per plu tenu folia de kriso. An plu oku pa es bi brilo safira; e u mega rubi-li pa
brilo epi u manu-ra de an gladia.

Plu persona pa fo admira an. “An es iso kali de u klima-galina,” pa dice mo urba
koncili-pe qi pa volu gene famo de habe boni arti ski; “sed ne tanto uti-ple” an pa pluso;
este plu persona posi doxo: an pa es no-praxi. Veri, an pa es u fo praxi-an.

“Qo-ka tu ne es simi un Hedo Prince?” pa qestio u sofi matri de fe pusi ju-an; an pa du
lakrima pro panto-ra. Un Hedo Prince zero-kron puta de lakrima pro ali-ra.”

“Mi este hedo hedo; es uno-pe in munda qi es fo hedo.” Pa murmura u ge-frustra andro tem
an skope ad u sti-mira statua.

“An feno iso un angela,” pa dice plu Karita Infanti tem mu pa ki ex u katedrala; ge-vesti
per mu fo rubi toga e mu puri leuko alexi-ve.

“Komo tu ski?” pa dice u matemati doci-an, “tu zero-kron pa vide mo.”

“A! na habe, tem na plu sonia,” pa reakti plu infanti. E u matemati doci-an pa fuga an
fronta e feno severi; kausa an ne amo de plu infanti qi sonia.

Mo noktu u pusi Hirundo pa peti supra u polita. Plu ami de an pa ki ab ad Egipti pre six
meno; sed an ne pa ki ko mu; kausa an filo u fo kali Tifa. An pa enkontra fe tosto
blasto-tem, tem an pa peti kata potami poste u mega xanto falena. An pa este ta atrakti a
fe tenu meso-soma; seqe-co, an pa sto te dice ko fe.

“Qe tu volu mi filo tu?” pa dice un Hirundo; an zero-kron pa disipa plu lexi. U Tifa pa
klino fo bato ad an. Seqe-co, an pa peti peri e peri fe; tange un aqa per an plu ala; e pa
face plu argenti pusi unda. U-ci pa es an filo-sporta; e an pa akti id tem un holo estiva.

“Id es u fatuo filo,” pa kanto plu hetero Hirundo; “fe habe zero valuta, e tro poli famili
membra.” E veri, pa es u fo mega numera de plu Tifa in potami. Po-co, kron sperma-tem pa
proto, panto Hirundo pa peti ab.

Po, mu pa peti ab, an pa este solito; e an pa proto gene fatiga de an filo-fe. “Fe habe
zero konversa;” an pa dice. “Mi este fobo; fe solo sporta ko filo; ka fe freqe filo-sporta
kon u venti.” E veri, panto-kron u venti pa fla; u Tifa gratioso pa flxi se. “Mi konfesi;
fe es u domi filo-fe,” an pa kontinu; “sed mi fo amo viagia; e seqe-co, mi gina plus, debi
fo amo viagia.”

“Qe tu fu ki ab ko mi?” an fini pa qestio a fe; sed u Tifa pa dice no per fe kefa; fe tro
mega amo fe eko-lo.

“Tu pa sporta ko mi,” an pa voka. “Mi fu ki ad plu Piramida. Vale!” E an pa peti ab.

Un holo di an pa peti; e noktu-tem an pa veni ad u polita. “Qo-lo mi pote reposa?” an pa
dice; mi spe; u polita pre nu prepara pro mi.” Po-co, an pa vide u statua ep un alto
kolumni. “Mi fu reposa la”, an pa voka. “Id es u kali loka, ko mega puri aero.” Seqe-co,
an pa sedi inter plu pedi de un Hedo Prince. “Mi habe u kriso somni-ka,” an pa dice qieto
a se tem skope peri an; e an pa prepara proto somni. Sed tem an pa du loka an kefa infra
an ala; u mega guta de aqa pa kade epi an. “U-la es fo qestio!” an pa voka. “Es zero nefa
in urani; plu astro brilo klari; sed id pluvi. U klima in boreo Europa veri es fo mali. U
Tifa pa amo u pluvi; sed u-la pa es solo kausa fe pa es egoisti.”

Po-co, un hetero guta pa kade. “Qo-uti habe u statua si id ne protekti mi anti pluvi?” an
pa dice. “Mi nece cerka u fumi-tubi.” An pa decide de peti ab.

Sed pre an aperi plu ala; guta tri pa kade; e an pa skope ana, e pa vide --- a! an pa vide
qo-ra?

Plu oku de un Hedo Prince pa es ge-ple per plu lakrima; e plu lakrima pa du kade kata an
plu kriso buka. An facia pa es fo kali in luna-lumi; e u pusi Hirundo pa es ge-ple ko
simpati.

“Qo-pe tu es?” an pa dice.

“Mi es un Hedo Prince.”

“Qo-ka tu lakrima?” pa qestio un Hirundo; “tu pa sti aqa mi.”

“Tem mi pa vive e pa habe un homi kardia,” pa reakti u statua; “mi ne pa ski de plu
lakrima. Mi pa eko in Palati Sans-Sourci; pe ne pa lice tristi la. Tem plu di mi pa sporta
ko plu ami in un horti; e tem plu vespera mi pa duce u kore in u Mega Atria. Peri un horti
pa es un alti mura; sed mi zero-kron pa qestio qo-ra es ultra id; panto-ra peri mi pa es
kali. Mi plu korta-pe pa nima mi un Hedo Prince; e veri mi pa es fo hedo; si pe nima
delekta es hedo. So mi pa vive e so mi pa morta. E nu mi es morta; pe pa loka mi ana ci
tanto alti; mi pote vide panto no-kali e non-hedo de mi polita; mi kardia gene face per
plumba; anti-co mi ne pote sto se de lakrima.”

“ Qo! Qe an ne pa gene face per solidi kriso?” pa dice un Hirundo a se. An pa es tro
civili de alti-voci ali persona doxo.

“Tele ab,” pa kontinu u statua in baso e musika voce, “tele ab in pusi via es u povi domi.
Mo de plu fenestra es aperi; e dia id mi pote vide u gina sedi ante u tabla. Fe facia es
tenu e anxio; fe habe no-glabro e rubi plu manu; mu es ge-punge per aku; kausa fe es u
sue-fe. Fe nu sue plu pasiflori ad epi u satina-roba pro u maxi kali de plu servi-fe de u
Fe-regi; fe fu es ge-vesti per id tem u fu Korta-kore. In u kli in gono de u kamera kumbe
fe pusi ju-an; an es pato. An habe u febri; e an petitio plu orange. An matri habe zero-ra
de dona ad an exclude potami-aqa; seqe-co, an du lakrima. Hirundo, pusi Hirundo, qe tu fu
fero a fe u rubi-li ex mi gladia manu-ra? Mi plu pedi es ge-fixa ad u-ci pedi-sta; e mi ne
pote kine.”

“Pe atende mi in Egipti,” pa dice un Hirundo. “Mi plu ami nu peti ana e kata u Nile; e mu
du dice a plu mega lotus-flori. Mu nu-fu somni in tafo de u mega An-regi. Un An-regi auto
es la in an ge-kroma morta-va. An es ge-tegu in xanto-te e ge-preserva per plu kondimenta.
Peri an cervika es u katena de leuko-klori klori-li; e plu manu es simi plu
ge-sika-folia.”

“Hirundo, pusi Hirundo,” pa dice u Prince, “Qe tu pote resta ko mi solo tem mo moktu; te
es mi angeli? U ju-an habe mega dipso; e an matri es ta tristi.”

“Mi ne doxo; mi amo plu ju-an,” pa reakti un Hirundo. “Pa estiva tem mi resta para potami;
pa es bi no-civili ju-an; mu pa es plu an-fili de u Molina-an; e mu freqe pa bali plu
kalkula a mi. Sura, mu zero-kron pa tange mi; plu Hirundo peti mega tro tekno pro u-la; e
plus-co mi veni ex u famili qi es famo pro id agili; sed, mi doxo; plu ju-an ne respekti
mi.”

Sed un Hedo Prince pa feno ta non-hedo; e u pusi Hirundo pa este penito. “Id es fo frigid
ci,” an pa dice; “sed mi fu resta ko tu pro mo noktu; e fu es tu angeli.”

“Gratia, pusi Hirundo,” pa dice u Prince. Seqe-co, un Hirundo pa prende u mega rubi-li ex
gladia de u Prince; e an pa peti ab ko id intra an rostra; an pa ki supra plu stego de u
polita. An pa pasa u turi de u katedrali; ko id ge-skulptu plu leuko marmora angeli. An pa
pasa u Palati; e an pa audi u soni de kore. U kali gina pa veni ex ad epi u balkoni ko fe
filo-an. “Ta sti mira plu astro es nu-noktu,” an pa dice a fe; e ta sti mira es u dynamo
de filo!” “Mi spe; mi roba fu es ge-fini pro u Stata-Kore,” fe pa reakti. “Mi pa petitio
plu pasiflori de gene sue ad epi id; sed u sue-fe e ta anti-ergo.”

An pa pasa supra u potami; e pa vide plu pusi-lampa pende epi plu navi-pali. An pa pasa
supra u paleo mero polita topo plu Semiti-pe eko; e pa vide mu negotia kon alelo; e ponde
valuta in plu kupra-libra. Fini, an pa veni a povi domi e pa skope in. U ju-an pa torto e
tropi se ko febri in an kli. An matri pa du somni; fe pa es ta fatiga. An pa salta in; e
pa loka u mega rubi-li ad epi u tabla para u digi alexi-ra de u sue-fe. Po-co, an pa peti
gentili peri u kli; te fla u fronta de u ju-an per an plu ala. “Mi nu este fresco!” pa
dice u ju-an; “posi mi nu gene repara. Po-co, an pa reposa kon hedo somni.

Po-co, un Hirundo pa peti versi ad un Hedo Prince; e pa explika ad an qod an nu-pa akti.
“Strano!” An pa dice; “nu mi este subo termo; sed id es ta frigid ci.”

“U-la es kausa tu pa boni akti,” pa dice u Prince. E u pusi Hirundo pa proto de puta;
po-co, an pa somni. Puta panto-kron pa sti somni an.

Proto de u fu di; an pa peti kata a potami te balno se. “U fo strano fenomeno!” pa dice u
Profesora de Ornitologi tem a pa pasa supra ponti. “Un Hirundo in hiberna!” E an pa grafo
u longi grama de id a loka nova-papira. Panto-pe pa cita id; id pa es ge-ple de poli lexi
qi mu ne pa logi.

“Nu noktu mi ki ad Egipti,” pa dice un Hirundo; e an pa este fo hedo puta de id. An pa
visita panto plu famo memo-ra; e pa sedi longi tem epi u koni-stego de u religio-do.
Panto-lo an pa ki, plu Paseri pa kanta ad alelo; “u fo kali strano-avi!” Seqe-co, an pa
mega fru se. Tem u luna pa ki ana; an pa peti versi ad un hedo prince. “Qe tu habe ali
ergo-petitio in Egipti?” an pa voci; mi nu-fu proto mi viagia.”

“Hirundo, Hirundo, pusi Hirundo,” pa dice u prince, “qe tu fu resta ko mi solo mo plus
noktu?”

“Pe atende mi in Egipti,” pa reakti un Hirundo. “Fu-di mi plu ami peti ana Katarakta Bi.
Plu potami-hipo jace la inter plu Skirpus; e epi u mega granita-do sedi u Teo Memnon. Tem
un holo noktu an skope plu astro; e kron u matina astro brilo; an voci u kri de hedo;
po-co, an es no-soni. Meso-di, plu xanto leo veni a margina de aqa te bibe. Mu habe plu
oku iso plu mega xanto-li; e mu roar es ma voci de u roar-soni de u katarakta.”

“Hirundo, Hirundo, pusi Hirundo,” pa dice u Prince, “tele ab trans polita mi vide u juve
andro in u stego-ka. An klina supra u grafo-tabla qi es ge-tegu ko plu papira; in
steno-vasa para an es plu morta viola. An kapila es bruno e krispa; an plu labia es iso
rubi de u pomegranata; e an habe plu mega sonia oku. A tenta fini grafo u spektakla pro u
Direktora de u Teatra; sed an es tro frigid de kontinu grafo. Es zero piro in piro-lo; e
an este fatiga de famina.”

“Mi fu resta ko tu mo pluso noktu,” pa dice un Hirundo; veri, an habe u boni kardia. “Qe
mi fero ad an un hetero rubi-li?”

“Mali-fortuna! Mi nu ne habe ali rubi-li,” pa dice u Prince. “Mi habe nu solo mi plu oku.
Mu es ge-face ex plu rari ciano-li; mu pa veni ex India mo kilo anua retro. Prende mo de
mu e fero id ad an. An fu vendo in a gema-an; e merka piro-xila; e po-co, an fu fini an
spektakla.”

“Karo prince,” pa dice un Hirundo, “mi ne pote akti u-la”; e an pa proto de lakrima.

“Hirundo, Hirundo, pusi Hirundo,” pa dice u prince, “akti qod mi komanda.”

Seqe-co, un Hirundo pa prende un oku de u Prince; e pa peti ad u stego-ka de u stude-an.
Id pa es fo facili de ki in; kausa pa es u for a in u stego. An pa peti tako dia id; e pa
ki ad in kamera. U juve andro pa habe an kefa ge-tegu per an plu manu; seqe-co, an ne pa
audi u soni de plu ala de un avi; kron an pa skope ana an pa detekti u kali ciano-li kumbe
epi plu morta viola.

“Pe proto valu mi,” an pa voci; “u-ci veni ex uno-pe qi fo admira mi. Nu mi pote fini mi
spektakla;” e an pa feno fo hedo.

U fu-di un Hirundo pa peti kata ad un asila. An pa sedi epi navi-pali de u mega navi e pa
skope plu navi-pe tira plu mega teka ex kargo-ka per plu funi. “Tira a-hoi!” Mu pa fo soni
voci tem singu teka pa veni ana. “Mi ki ad Egipti!” pa voci un Hirundo; sed zero-pe pa
audi; kron u luna pa proto ki ana an pa peti versi ad un Hedo Prince.

“Mi pa veni te dice vale,” an pa voci.

“Hirundo, Hirundo, pusi Hirundo,” pa dice u Prince; “Qe tu fu resta solo mo pluso noktu ko
mi?”

“Id es hiberna,” pa reakti un Hirundo, “e u ma frigid klima nu fu veni. In Egipti un heli
es termo epi plu kloro Palma-dendro; e plu krokodilus jace in u limo e skope anti-ergo
peri mu. Plu ami de mi nu tekto u nidi in Templa de Baalbek; e plu rosa e leuko kolumba
skope mu; e mu filo-kanta ad alelo. Karo Prince, mi nece ki ab; sed mi zero-kron fu
no-memo tu; e fu blasto-tem mi fu fero a tu bi kali gema te vice bi-la gema qi tu pa dona
ab. U rubi-li fu es ma rubi de u rubi rosa; e u ciano-li fu es ma ciano de u mega mari.”

“In u qadra infra na,” pa dice un Hedo Prince, “ sta u pusi flami-fero ju-fe. Fe pa lase
kade plu flami-fero ad in aqa-kanali para pedi-via; mu ne es no-funktio. Fe patri fu bato
fe; si fe ki a domi minus ali valuta; e fe nu lakrima. Fe habe zero pedi-ve alo poda-ve; e
zero tegu epi fe kefa. Prende mi hetero oku; e dona id a fe; e fe patri ne fu bato fe.”

“Mi fu resta ko tu mo pluso noktu,” pa dice un Hirundo, “sed mi ne pote uti tu hetero oku.
Tu ne sio pote vide.”

“Hirundo, Hirundo, pusi Hirundo,” pa dice u Prince, “akti qod mi komanda.”

Seqe-co an pa prende un hetero oku de u Prince; e pa peti tako kata ko id. An pa baso peti
pasa u flami-fero ju-fe; e pa lase kade u gema in meso de fe manu. “U fo kali mero vitri!”
pa voci u ju-fe; e fe pa dromo a fe domi tem ridi.

Po-co, un Hirundo veni versi ad u Prince. “Tu ne pote vide nu,” an pa dice, “seqe-co, mi
fu resta ko tu panto-tem.”

“No, pusi Hirundo, “ pa dice u povi prince, “tu nece ki ab ad Egipti.” “Mi fu resta ko tu
panto-tem,” pa dice un Hirundo; e an pa somni para plu pedi de u Prince.

Holo u fu-di an pa sedi epi skapa de u Prince; e an pa dice an plu stori de plu-la ra an
pa vide in plu xeno landa. An pa dice de plu rubi aqa-avi; qi sta in plu longi line epi
plu ripa de u Nile; e mu kapti kriso-piski in mu plu rostra. An pa dice de u Sfinx; qi es
iso palaeo de u munda auto; e eko in u deserta; e id ski panto-ra. De plu merka-pe qi
no-tako gresi para mu Kamelus e fero plu xanto globula in mu plu manu. De un An-regi de u
Monti e de u Luna; qi es iso melano de eboni; e qi latri u mega kristali. De u mega kloro
serpenti qi somni in Palma-dendro; e qi habe bi-ze preka-pe de nutri id ko plu meli-plaka.
E de plu Pusi-pe; qi veli supra u mega laku epi plu mega e plati folia; e mu panto-kron
milita ko plu papilio.

“Karo pusi Hirundo,” pa dice u Prince, “tu dice a mi de plu sti mira kosa; sed klu ma sti
mira es u sufere de plu andro e plu gina. Es zero hetero misteri iso mega de non-hedo.
Peti supra mi polita; pusi Hirundo; e dice a mi qod tu vide la.”

Seqe-co, un Hirundo pa peti supra u grandi polita; e pa vide plu Pluto-pe amusa se in mu
plu kali domi; iso kron plu mendika-pe sedi ante plu horti porta. An pa peti ad in plu
skoto steno-via; e pa vide plu leuko facia de plu ge-famina infanti qi skope minus
interese a plu melano via. Infra un arca de u ponti; bi ju-an pa kumbe kon alelo te tenta
tena se termo. “Na es fo famina!” mu pa dice. “Tu ne lice kumbe la” pa voci u skope-pe; e
mu pa vaga ab in u pluvi.

Po-co, an pa peti versi; e pa explika ad u prince qod an pa vide.

“Mi es ge-tegu per mega-valu kriso;” pa dice u Prince. “Tu nece prende id ab, folia po
folia; e dona id a plu pove-pe; plu vive-pe panto-kron doxo; kriso sti hedo mu.”

Folia po folia de u mega-valu kriso un Hirundo pa prende ab; a kron un Hedo Prince pa feno
no-brilo e polio. Folia po folia de u mega-valu kriso an pa fero a plu pove-pe; plu facia
de plu infanti pa esce ma rosa; e mu pa ridi e pa sporta in u via. “Na nu habe pani!” mu
pa voci.

Po-co, pa veni u nivi; e po u nivi pa veni u krista. Plu via pa feno; mu pa es ge-face ex
argenti; nu mu es ta brilo e scintili; plu longi kristali-daga pa pende kata ex plu stego
de plu domi. Panto-pe pa gene vesti per plu pila-ve; e plu pusi ju-an pa habe plu rubi
kefa-ve; e mu pa glisa epi u glacia.

U pove pusi Hirundo pa gene ma frigid e ma frigid; sed an ne pa linqe u Prince; an tanto
pa filo an. An pa vora plu pani mika extra u porta de u pani-bo; kron u pani-pe ne pa
skope; e an pa tenta tena se termo per kine an plu ala ana e kata.

Sed fini, an pa ski; an nu-fu lose bio. An pa habe solo sati dina te peti ana e ad epi u
skapa de u Prince. “Vale, karo Prince!” an pa murmura. “Qe mi lice oskula tu manu?”

“Mi es hedo; tu fini fu ki ad Egipti, pusi Hirundo.” Pa dice u Prince. “Tu pa resta ci tro
longi tem; sed tu nece oskula mi epi plu labia; ka mi filo tu.”

“Mi ne fu ki ad Egipti,” pa dice un Hirundo. “Mi fu ki a Domi de Morta. Morta es u fratri
de Somni, qe?” E an pa oskula un Hedo Prince epi plu labia; e pa lose bio e pa kade a plu
pedi de un Hedo Prince.

U-la kron u strano krak pa soni intra u statua; qasi uno-ra pa gene frakti. Veri, u plumba
kardi pa frakti ad in bi mero. Sura, id pa es u forti Krista.

Tosto u fu matina un urba-cefa pa du gresi in qadra infra ko plu urba koncili-pe. Tem mu
pa pasa u kolumni an pa skope ana ad u statua. “Karo mi un Hedo Prince feno fo no-puri;”
an pa dice.

“An veri es fo no-puri!” Pa dice plu urba koncili-pe; mu panto-kron pa akorda kon mu cefa;
e mu pa skope ana ad id.

“U rubi-li pa kade ab an gladi; e plu oku ne es la; e an ne dura habe u kroma de kriso;”
pa dice u cefa; “veri an feno u mendika-pe!”

“Veri, an feno u mendika-pe,” pa dice plu urba koncili-pe. “E es klu u morta avi para a
pedi!” pa kontinu u urba-cefa. “Na nece face u proklama; plu avi ne lice lose bio ci.” E
un urba buro-pe pa grafo u-ci sugesti.

Seqe-co, mu pa prende kata u statua de un Hedo Prince. “Kausa an nu ne es kali; an nu habe
zero uti,” pa dice un Arti Profesora in un Universita.

Po-co, mu pa liqi u statua in u furna; un urba-cefa pa akorda un unio de u Korporati te
decide un uti de u metali. “Sura, na nece habe un hetero statua,” an pa dice; “e id fu es
u statua de mi auto.”

“De auto,” pa dice singu de plu urba koncili-pe; e mu pa disputa. U pre-kron mi audi de
mu; mu pa du disputa.

“Qo strano-ra!” pa dice u skope-pe de plu face-pe in furna-do. “U-ci ge-frakti plumba
kardia ne fu liqi in u furna. “Na nece bali id ab.” Seqe-co, mu pa bali id epi disipa kumu
topo u morta Hirundo pa kumbe.

“Fero a mi; bi-la ra qi habe u maxi mega valu in u polita,” pa dice Teo a mo de plu
Angeli. E un Angeli pa fero ad An u plumba kardia e u morta avi.

“Tu pa sofi elekti,” pa dice Teo. “Ka in mi horti de Paradisi u-ci pusi avi fu kanta
panto-tem; e in mi polita de kriso un Hedo Prince fu lauda mi.”

